name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker Image
      run: docker build --tag ${{secrets.DOCKER_USER}}/hangman:latest
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/hangman:latest
